language: bash
sudo: true
notifications: {
  "email": false,
  "irc": {
    "channels": ["ircs://irc.spi.gt:6697/#MiniDigger"],
    "on_success": "change",
    "on_failure": "always",
    "skip_join": true
  }
}
script: "chmod +x scripts/build.sh && scripts/build.sh"
deploy:
  provider: script
  script: "chmod +x scripts/deploy-build-results.sh && scripts/deploy-build-results.sh"
  on:
    branch: master
  skip_cleanup: true
