site_name: VoxelGamesLib Documentation
site_description: Developer documentation for VoxelGamesLib v2
site_author: VoxelGamesLib

theme: readthedocs

pages:
- Introduction: index.md
- Doctrine: doctrine.md
- Getting started: getting-started.md
- Components: components.md
- Maps: maps.md
- Contributors: contributors.md

markdown_extensions:
  - admonition
