site_name: VoxelGamesLib Documentation
site_description: Developer and user documentation for VoxelGamesLib v2
site_author: VoxelGamesLib

repo_name: 'VoxelGamesLib'
repo_url: 'https://github.com/VoxelGamesLib/docs'

copyright: 'Copyright &copy; 2016 - 2017 VoxelGamesLib and Contributors'

theme: 'material'

edit_uri: 'blob/master/docs/'

pages:
- Introduction: index.md
- General:
  - Doctrine: general/doctrine.md
  - Getting started: general/getting-started.md
  - Terms: general/terms.md
- Maps:
  - Introduction: maps/introduction.md
  - How to create a map: maps/how-to-create-a-map.md
- Components:
  - General: components/general.md
  - Features: components/features.md
  - Phases: components/phases.md
  - Games: components/games.md
- Developer Area:
  - How to write a feature: developer-area/how-to-write-a-feature.md
  - How to write a phase: developer-area/how-to-write-a-phase.md
  - How to write a game: developer-area/how-to-write-a-game.md
- Contributor Area:
  - General: contributor-area/general.md
  - Contributors: contributor-area/contributors.md
  - Contribute Code: contributor-area/contribute-code.md
  - Contribute Maps: contributor-area/contribute-maps.md
  - Contribute Translations: contributor-area/contribute-translations.md
  - Create bug reports or feature requests: contributor-area/create-bug-reports-or-feature-requests.md
  - Contributor's Corner: contributor-area/contributors-corner.md
- Test:
  - Test: test/testpage.md

extra:
  palette:
    primary: 'amber'
    accent: 'orange'
  logo: 'images/logo.svg'
  social:
    - type: 'github'
      link: 'https://github.com/VoxelGamesLib'
    - type: 'twitter'
      link: 'https://twitter.com/xMiniDiggerx'
  feature:
    tabs: true

markdown_extensions:
  # notes quotes etc
  - admonition
  # code highlights
  - codehilite(linenums=true)
  # footnotes
  - footnotes
  # table of contents, permalinks
  - toc(permalink=true)
  # bunch of random crap
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde